//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoEmailer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoEmailer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///
        ///&lt;title&gt;GLI Email Signature&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///body,td,th {
        ///    font-family: Cambria, &quot;Hoefler Text&quot;, &quot;Liberation Serif&quot;, Times, &quot;Times New Roman&quot;, serif;
        ///    font-style: normal;
        ///    font-size: 14px;
        ///    color: #343434;
        ///}
        ///body {
        ///    background-color: #FFFFFF;
        ///}
        ///a:link {
        ///    color: #152f55;
        ///    text-decoration: none;
        ///}
        ///a:visited {
        ///    text-decoration: none;
        ///    color: #152f55;
        ///}
        ///a:hover {
        ///    text-decoration: none;
        ///} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultEmail {
            get {
                return ResourceManager.GetString("DefaultEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;!-- saved from url=(0040)https://gaminglabs.com/emails/email.html --&gt;
        ///&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///
        ///&lt;title&gt;GLI Email Signature&lt;/title&gt;
        ///&lt;style type=&quot;text/css&quot;&gt;
        ///body,td,th {
        ///    font-family: Cambria, &quot;Hoefler Text&quot;, &quot;Liberation Serif&quot;, Times, &quot;Times New Roman&quot;, serif;
        ///    font-style: normal;
        ///    font-size: 14px;
        ///    color: #343434;
        ///}
        ///body {
        ///    background-color: #FFFFFF;
        ///}
        ///a:link {
        ///    color: #152f55;
        ///    text-decoration: none;
        ///}
        ///a:visited {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GLI_Email_Signature {
            get {
                return ResourceManager.GetString("GLI_Email_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_graphic_bottom_385x20 {
            get {
                object obj = ResourceManager.GetObject("x_graphic_bottom_385x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_graphic_GLI_logo_short_version {
            get {
                object obj = ResourceManager.GetObject("x_graphic_GLI_logo_short_version", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_graphic_side_long_version {
            get {
                object obj = ResourceManager.GetObject("x_graphic_side_long_version", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_graphic_sm_icons_FB {
            get {
                object obj = ResourceManager.GetObject("x_graphic_sm_icons_FB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_graphic_sm_icons_IN {
            get {
                object obj = ResourceManager.GetObject("x_graphic_sm_icons_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_graphic_sm_icons_LI {
            get {
                object obj = ResourceManager.GetObject("x_graphic_sm_icons_LI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x_graphic_sm_icons_TW {
            get {
                object obj = ResourceManager.GetObject("x_graphic_sm_icons_TW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
